# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
- repo: https://github.com/golangci/golangci-lint
  rev: v1.46.2
  hooks:
    - id: golangci-lint
- repo: https://github.com/Bahjat/pre-commit-golang
  rev: v1.0.0
  hooks:
    - id: go-fmt-import
    - id: go-vet
    - id: go-lint
    - id: gofumpt # requires github.com/mvdan/gofumpt
    - id: go-err-check # requires github.com/kisielk/errcheck
    - id: go-static-check # install https://staticcheck.io/docs/
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-critic
    - id: go-build
    - id: go-mod-tidy
    - id: go-unit-tests
