name: Go

on:
  push:
    branches:
        - main
        - release/*
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go test -v -coverpkg=github.com/tjs-w/go-proto-stomp/pkg/stomp/... -coverprofile=profile.cov ./...
        go tool cover -func profile.cov
