name: Release

on:
  push:
    # run only against tags
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build stompd
        uses: goreleaser/goreleaser-action@v3.0.0
        with:
          args: build --rm-dist --config .goreleaser.yaml
          workdir: cmd/stompd/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build stomper
        uses: goreleaser/goreleaser-action@v3.0.0
        with:
          args: build --rm-dist --config .goreleaser.yaml
          workdir: cmd/stomper/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release stompd
        uses: goreleaser/goreleaser-action@v3.0.0
        with:
          args: release --rm-dist --config .goreleaser.yaml
          workdir: cmd/stompd/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release stomper
        uses: goreleaser/goreleaser-action@v3.0.0
        with:
          args: release --rm-dist --config .goreleaser.yaml
          workdir: cmd/stomper/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release go-proto-stomp module
        run: |
          release=$(git describe --tags --abbrev=0)
          echo "Release version: ${release}"
          GOPROXY=proxy.golang.org go list -m github.com/tjs-w/go-proto-stomp@${release}
